[build]
builder = "nixpacks"

[[services]]
name = "api"
root = "api"
startCommand = "sh -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT'"

[[services]]
name = "web"
root = "app"
startCommand = "dhttpd --path build/web --port $PORT"

